# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 300))
        MainWindow.setStyleSheet("QScrollBar:vertical {\n"
"    width: 1px\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.drop_shadow_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.drop_shadow_layout.setContentsMargins(10, 10, 10, 13)
        self.drop_shadow_layout.setSpacing(0)
        self.drop_shadow_layout.setObjectName("drop_shadow_layout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.drop_shadow_frame.setFont(font)
        self.drop_shadow_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.534091 rgba(0, 0, 30, 255), stop:0.761364 rgba(0, 0, 50, 255));\n"
"border-radius: 10px;\n"
"")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("background-color: none")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_2.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(0, 255, 255);")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_2.addWidget(self.label_title)
        self.frame_fkeys = QtWidgets.QFrame(self.frame_title)
        self.frame_fkeys.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fkeys.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fkeys.setObjectName("frame_fkeys")
        self.btn_save = QtWidgets.QPushButton(self.frame_fkeys)
        self.btn_save.setGeometry(QtCore.QRect(227, 11, 24, 16))
        self.btn_save.setText("")
        self.btn_save.setObjectName("btn_save")
        self.btn_save_as = QtWidgets.QPushButton(self.frame_fkeys)
        self.btn_save_as.setGeometry(QtCore.QRect(154, 11, 24, 16))
        self.btn_save_as.setText("")
        self.btn_save_as.setObjectName("btn_save_as")
        self.btn_open = QtWidgets.QPushButton(self.frame_fkeys)
        self.btn_open.setGeometry(QtCore.QRect(82, 11, 24, 16))
        self.btn_open.setText("")
        self.btn_open.setObjectName("btn_open")
        self.btn_doc_close = QtWidgets.QPushButton(self.frame_fkeys)
        self.btn_doc_close.setGeometry(QtCore.QRect(9, 11, 24, 16))
        self.btn_doc_close.setText("")
        self.btn_doc_close.setObjectName("btn_doc_close")
        self.horizontalLayout_2.addWidget(self.frame_fkeys)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_min = QtWidgets.QPushButton(self.frame_btns)
        self.btn_min.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_min.setMaximumSize(QtCore.QSize(17, 17))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(False)
        self.btn_min.setFont(font)
        self.btn_min.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.btn_min.setText("")
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_3.addWidget(self.btn_min)
        self.btn_max = QtWidgets.QPushButton(self.frame_btns)
        self.btn_max.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_max.setMaximumSize(QtCore.QSize(17, 17))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_max.setFont(font)
        self.btn_max.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_max.setText("")
        self.btn_max.setObjectName("btn_max")
        self.horizontalLayout_3.addWidget(self.btn_max)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.title_bar)
        self.contents_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.contents_bar.setStyleSheet("background-color: none")
        self.contents_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contents_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contents_bar.setObjectName("contents_bar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.contents_bar)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textEdit = QtWidgets.QTextEdit(self.contents_bar)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.534091 rgba(0, 0, 30, 255), stop:0.761364 rgba(0, 0, 50, 255));\n"
"\n"
"color: rgba(0, 255, 255, 255);\n"
"\n"
"border: 1px solid rgba(0, 255, 255, 25);")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_5.addWidget(self.textEdit)
        self.verticalLayout.addWidget(self.contents_bar)
        self.credits_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.credits_bar.setStyleSheet("background-color: none")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_4.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.credits_label_frame = QtWidgets.QFrame(self.credits_bar)
        self.credits_label_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.credits_label_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_label_frame.setObjectName("credits_label_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.credits_label_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_credits = QtWidgets.QLabel(self.credits_label_frame)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(85, 255, 255);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_6.addWidget(self.label_credits)
        self.frame_status = QtWidgets.QFrame(self.credits_label_frame)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.frame_status.setFont(font)
        self.frame_status.setStyleSheet("color: rgb(85, 255, 255);")
        self.frame_status.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_status.setObjectName("frame_status")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_status)
        self.horizontalLayout_7.setContentsMargins(250, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_status = QtWidgets.QLabel(self.frame_status)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_7.addWidget(self.label_status)
        self.horizontalLayout_6.addWidget(self.frame_status)
        self.horizontalLayout_4.addWidget(self.credits_label_frame)
        self.frame_grip = QtWidgets.QFrame(self.credits_bar)
        self.frame_grip.setMaximumSize(QtCore.QSize(25, 16777215))
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_4.addWidget(self.frame_grip)
        self.verticalLayout.addWidget(self.credits_bar)
        self.drop_shadow_layout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Untitled"))
        self.btn_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.btn_save_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.btn_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.btn_doc_close.setShortcut(_translate("MainWindow", "Ctrl+Shift+Backspace"))
        self.label_credits.setText(_translate("MainWindow", "By: Harish"))
        self.label_status.setText(_translate("MainWindow", "Untitled"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
