# Form implementation generated from reading ui file 'assets/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QScrollBar:vertical {\n" "    width: 1px\n" "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.drop_shadow_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.drop_shadow_layout.setContentsMargins(0, 0, 0, 0)
        self.drop_shadow_layout.setSpacing(0)
        self.drop_shadow_layout.setObjectName("drop_shadow_layout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.drop_shadow_frame.setFont(font)
        self.drop_shadow_frame.setStyleSheet(
            "border-radius: 10px;\n" "background-color: rgb(34, 46, 65);"
        )
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(0, 3, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.title_bar.setStyleSheet("background-color: none")
        self.title_bar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_hotkey = QtWidgets.QPushButton(self.title_bar)
        self.btn_hotkey.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_hotkey.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.btn_hotkey.setStyleSheet(
            "color: #53c6ba;\n"
            "\n"
            "background-color: #0E131B;\n"
            "\n"
            "border-radius: 5;"
        )
        self.btn_hotkey.setObjectName("btn_hotkey")
        self.horizontalLayout.addWidget(self.btn_hotkey)
        self.frame_fkeys = QtWidgets.QFrame(self.title_bar)
        self.frame_fkeys.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_fkeys.setMaximumSize(QtCore.QSize(0, 0))
        self.frame_fkeys.setStyleSheet("")
        self.frame_fkeys.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_fkeys.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_fkeys.setObjectName("frame_fkeys")
        self.btn_save = QtWidgets.QPushButton(self.frame_fkeys)
        self.btn_save.setGeometry(QtCore.QRect(227, 11, 0, 0))
        self.btn_save.setMaximumSize(QtCore.QSize(0, 0))
        self.btn_save.setText("")
        self.btn_save.setObjectName("btn_save")
        self.btn_save_as = QtWidgets.QPushButton(self.frame_fkeys)
        self.btn_save_as.setGeometry(QtCore.QRect(154, 11, 0, 0))
        self.btn_save_as.setMaximumSize(QtCore.QSize(0, 0))
        self.btn_save_as.setText("")
        self.btn_save_as.setObjectName("btn_save_as")
        self.btn_open = QtWidgets.QPushButton(self.frame_fkeys)
        self.btn_open.setGeometry(QtCore.QRect(82, 11, 0, 0))
        self.btn_open.setMaximumSize(QtCore.QSize(0, 0))
        self.btn_open.setText("")
        self.btn_open.setObjectName("btn_open")
        self.btn_file_close = QtWidgets.QPushButton(self.frame_fkeys)
        self.btn_file_close.setGeometry(QtCore.QRect(9, 11, 0, 0))
        self.btn_file_close.setMaximumSize(QtCore.QSize(0, 0))
        self.btn_file_close.setText("")
        self.btn_file_close.setObjectName("btn_file_close")
        self.horizontalLayout.addWidget(self.frame_fkeys)
        self.label_title = QtWidgets.QLabel(self.title_bar)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: #53c6ba;")
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.label_title)
        self.spacer1 = QtWidgets.QFrame(self.title_bar)
        self.spacer1.setEnabled(False)
        self.spacer1.setMaximumSize(QtCore.QSize(0, 0))
        self.spacer1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.spacer1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.spacer1.setObjectName("spacer1")
        self.horizontalLayout.addWidget(self.spacer1)
        self.btn_close = QtWidgets.QPushButton(self.title_bar)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.btn_close.setFont(font)
        self.btn_close.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.btn_close.setStyleSheet(
            "QPushButton {\n"
            "    border: none;\n"
            "    border-radius: 8px;\n"
            "    background-color: rgb(253, 81, 67);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgba(254, 79, 69, 150);\n"
            "}"
        )
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout.addWidget(self.title_bar)
        self.contents_frame = QtWidgets.QFrame(self.drop_shadow_frame)
        self.contents_frame.setStyleSheet("background-color: #0E131B;")
        self.contents_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.contents_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contents_frame.setObjectName("contents_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.contents_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.editor_frame = QtWidgets.QFrame(self.contents_frame)
        self.editor_frame.setStyleSheet("background-color: #0E131B;")
        self.editor_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.editor_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.editor_frame.setObjectName("editor_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.editor_frame)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.editor = QtWidgets.QPlainTextEdit(self.editor_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editor.setFont(font)
        self.editor.setStyleSheet(
            "color: #e8c37d;\n"
            "\n"
            "background-color: #0E131B;\n"
            "\n"
            "border: 1px solid rgba(0, 255, 255, 25);\n"
            "\n"
            "border-radius: 10px;\n"
            "\n"
            "border: 0;"
        )
        self.editor.setPlainText("")
        self.editor.setObjectName("editor")
        self.horizontalLayout_4.addWidget(self.editor)
        self.size_grip_layout = QtWidgets.QVBoxLayout()
        self.size_grip_layout.setObjectName("size_grip_layout")
        self.horizontalLayout_4.addLayout(self.size_grip_layout)
        self.horizontalLayout_2.addWidget(self.editor_frame)
        self.verticalLayout.addWidget(self.contents_frame)
        self.drop_shadow_layout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_hotkey.setText(_translate("MainWindow", "H"))
        self.btn_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.btn_save_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.btn_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.btn_file_close.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.label_title.setText(_translate("MainWindow", "Untitled"))
        self.btn_close.setShortcut(_translate("MainWindow", "Ctrl+Shift+Q"))
